### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [osmhu/osmhu-website#71]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

Also, use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

cc: @fodor0205

---

Váltás az OAuth 2-re a HTTP Basic Auth-ról és az OAuth 1.0a-ról. Ezek elavultak.
Lásd: https://github.com/openstreetmap/operations/issues/867

Használja az `api.openstreetmap.org/api/` -és a HTTPS-t a `www.openstreetmap.org/api/*` helyett.
(Is: https://github.com/openstreetmap/operations/issues/951)

Megjegyzés, az `api.openstreetmap.org` API url jelenleg nem képes OAuth 2 handshake-et végrehajtani. Lásd https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
A `www.` alap URL és az `api.` API url szétválasztható. Lásd https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

( Fordítás: deepl.com/translator )

**Comment by mmd-osm** [comment]
@danieldegroot2 : I'm not sure if this project is using OAuth 1.0a at all. I see it in some test/ directory only, which appears to be some non-production code?

**Comment by danieldegroot2** [comment]
@mmd-osm Yes, I didn't always check. But if used in development environment or something it could still be good to notify them anyway.

**Comment by danieldegroot2** [comment]
Resolved by removing file https://github.com/osmhu/osmhu-website/commit/7ebe7852e6628d18603698f0e39af46ad9c05ec6
